### ISSUE TITLE
Installation instructions don't work

### ISSUE THREAD

**Issue by meelash** [jameswomack/Stylus-TextMate-Bundle#1]
The installation instructions don't work, at least for TextMate 2. The reason is that they say to clone the repo and name it Stylus.tmbundle, but the repo actually contains Stylus.tmbundle. So you end up with Bundles/Stylus.tmbundle/Stylus.tmbundle/, and textmate looks for the plist in the outer folder and can't find it.

Either the repo structure needs to change, or the instructions should change (I think the repo structure).

**Comment by jameswomack** [comment]
Instructions for install have been updated.
