### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [jameswomack/Stylus-TextMate-Bundle#2]
I would like to use your grammar for Stylus but I don't know what licensing terms you're distributing it under. Any chance you could pick one from here: http://choosealicense.com?

**Comment by pchaigno** [comment]
@jameswomack Did you get a chance to look into this? I'd like to use your grammar at [github/linguist](https://github.com/github/linguist) to highlight Stylus code on GitHub.

**Comment by jameswomack** [comment]
@pchaigno Let me add a license and commit. 
![I'll be back](http://media.giphy.com/media/JDKxRN0Bvmm2c/giphy.gif)

**Comment by jameswomack** [comment]
@pchaigno MIT license added.

**Comment by pchaigno** [comment]
Great! Thanks!
